name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
